name: ai-project-311
channels:
  - conda-forge
  - pytorch
  - pyg
dependencies:
  - python=3.11
  - matplotlib>=3.8.2
  - networkx>=3.2.1
  - numpy>=1.26.4
  - scikit-learn>=1.4.0
  - urllib3>=2.2.0
  - pytorch>=2.1.2
  - tqdm>=4.66.2
  - pyg>=2.5.0